version: '3'

services:
    yelp-backend:
        build: ./backend
        expose:
            - ${BACKEND_PORT}
        environment:
            BACKEND_PORT: ${BACKEND_PORT}
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        command: npm start

    yelp-frontend:
        tty: true
        build: ./frontend
        expose:
            - ${FRONTEND_PORT}
        environment:
            FRONTEND_PORT: ${FRONTEND_PORT}
        ports:
            - ${FRONTEND_PORT}:${FRONTEND_PORT}
        links:
            - yelp-backend